import { type ReactNode, useEffect, useState } from 'react';
import { LanguageContext } from './LanguageContext';

export type Language = 'en' | 'es';

const translations = {
  en: {
    languageLabel: 'Language', english: 'English', spanish: 'Spanish', multiplayerArena: 'Multiplayer Arena', competitiveLobby: 'Competitive Lobby', playersOnline: '{count} players online', inThisGame: '{count} in this game', player: 'Player', logOut: 'Log out', signIn: 'Sign in', register: 'Register', loadingSession: 'Validating session...',
    loadingLobby: 'Loading lobby...', centralLobby: 'Central lobby', chooseNext: 'Choose the next', fight: 'fight.', selectGame: 'Select a game', selectGameDescription: 'Select a game, check your rank, and jump into a match.', players: 'players', findingMatch: 'Finding match...', quickMatch: 'Quick match', arenas: 'arenas', loadingLeaderboard: 'Loading leaderboard...', loadingStats: 'Loading your stats...',
    selected: 'Selected', arena: 'Arena', playingNow: '{count} playing now', comingSoon: 'Coming soon', readyForMatch: 'Ready for match',
    myStats: 'My stats', personal: 'Personal', leaderboard: 'Leaderboard', wins: '{count}W',
    availableRooms: 'Available rooms', noRooms: 'No rooms available yet.', createFirstRoom: 'Create the first room', creator: 'Creator: {name}', playersInside: '{count} players inside', joinRoom: 'Join room',
    createRoom: 'Create room', newRoom: 'New room for {game}', close: 'Close', roomName: 'Room name', roomNamePlaceholder: 'Fleet Hunters', roomNameHelp: 'This is the visible name shown in Available Rooms.', cancel: 'Cancel', confirmRoom: 'Confirm room',
    failedLoad: 'Failed to load. Please try again.', retry: 'Retry', somethingWrong: 'Something went wrong', unexpectedError: 'An unexpected error occurred.', tryAgain: 'Try again', failedRooms: 'Failed to load rooms.', loadingMatchRoom: 'Loading match room...', playerOnline: '{count} player online', fastMatch: 'Quick match', back: 'Back',
    loginReturn: 'Competitive return', backToArena: 'Back to', theArena: 'the arena.', loginDescription: 'Check your progress, return to the lobby, and keep pushing your rank in competitive matches with a much clearer and livelier experience.', todayOn: 'Today on PlayHub', loginPromo: 'New duels, new streaks, new positions.', welcomeBack: 'Welcome back', loginPrompt: 'Sign in to your account and get back to competing where you left off.', email: 'Email', password: 'Password', enterPassword: 'Enter your password', hide: 'Hide', show: 'Show', signingIn: 'Signing in...', enterLobby: 'Enter the lobby', createAccount: 'Create account', forgotPassword: 'Forgot password?',
    newChallenger: 'New challenger', buildTag: 'Build your', playerTag: 'player tag.', registerDescription: 'Create your profile, enter the lobby, and start building history, streaks, and rank in every competitive arena.', whyJoin: 'Why join', registerPromo: 'Private rooms, visible stats, and progress you can feel in every match.', createYourAccount: 'Create your account', registerPrompt: 'Create your competitive profile and enter an ecosystem of matches, rankings, and stats.', username: 'Username', chooseUsername: 'Choose a username', createPassword: 'Create a password', confirmPassword: 'Confirm password', repeatPassword: 'Repeat your password', passwordStrength: 'Password strength:', startTyping: 'Start typing to measure', passwordsMismatch: 'Passwords do not match.', creatingAccount: 'Creating account...', createProfile: 'Create challenger profile', alreadyAccount: 'Already have an account?', weak: 'Weak', fair: 'Fair', good: 'Good', strong: 'Strong',
    realtimeMinigames: 'Multiplayer minigames in real time', playLoud: 'Play loud.', climbHarder: 'Climb harder.', presentationDescription: 'PlayHub turns competitive minigames into an experience with identity: live rooms, real rivals, clear stats, and an interface that makes you want to play again.', compete: 'Start competing', viewArenas: 'View arenas', livePulse: 'Live pulse', arenaPreview: 'Arena preview', online: 'online', seasonalFocus: 'Seasonal focus', seasonalCopy: 'Earn a place in the weekly top and unlock visible badges.', gameSelection: 'Game selection', chooseArena: 'Choose your arena', gamesDescription: 'Every game has its own rhythm, color, and tension. The goal is not just to play, but to return because your profile, ranking, and results matter.', loadingGames: 'Loading minigames...', readyNow: 'Ready now', comingNext: 'Coming next', registeredPlayers: 'Registered players', matchesPlayed: 'Matches played', onlineNow: 'Online now', activeArenas: 'Active arenas', quickMatches: 'Quick matches', quickMatchesCopy: 'Enter the lobby, choose a mode, and start competing in seconds.', realRivals: 'Real rivals', realRivalsCopy: 'Rooms, matchmaking, and live matches with other players.', visibleProgress: 'Visible progress', visibleProgressCopy: 'Rankings, history, and stats that turn every match into progress.', chooseMinigame: 'Choose a minigame with its own identity', competeLive: 'Compete live against other players', improveElo: 'Raise your ELO and improve your profile', duel: '1v1 duel', fastPace: 'Fast pace', pairs: '1v1 pairs', realtime: 'Real time', playing: '{count} playing',
    connected: 'Connected', connecting: 'Connecting', disconnected: 'Disconnected', room: 'Room {name}', ticTacToe: 'Tic-Tac-Toe', playerO: 'Player O', playersCount: '{count}/2 players', victory: 'Victory for {name}', draw: 'Draw', turn: '{name}\'s turn', yourTurn: 'Your turn', status: 'Status', restartGame: 'Restart game', backToLobby: 'Back to lobby', connectingRoom: 'Connecting to the room...', waitingSecond: 'Waiting for the second player.', gameStarted: 'The game has started.', gameRestarted: 'The game restarted.', playerLeft: 'A player left the room.', enteringRoom: 'Joining room {roomId}...', roomConnectFailed: 'Could not connect to the room.', moveRejected: 'The move was not accepted.', moveRecorded: 'The move was already recorded.', moveConfirmFailed: 'Could not confirm the move. Try again to reconcile the state.', restartFailed: 'Could not restart the game.', gameFinishedWinner: 'Game finished. {name} wins.', gameFinishedDraw: 'Game finished in a draw.',
    memoryPairs: 'Memory / Pairs', youPairs: 'You {count} pairs', youWin: 'You win.', opponentWins: 'Opponent wins.', resolvingCards: 'Resolving cards...', flipCard: 'Your turn: flip a card.', backMemory: 'Back to Memory lobby', gameInProgress: 'Game in progress.', flipRejected: 'Flip rejected.', flipConfirmFailed: 'The flip was not confirmed. Select the same card to retry safely.',
    triviaQuiz: 'Trivia quiz', answered: '{count}/10 answered', quizComplete: 'Quiz complete', resultsRecorded: 'Final results are recorded by the server.', backTrivia: 'Back to Trivia lobby', questionProgress: 'Question {current} of 10', answerIndependently: 'Answer independently. Wrong answers add five seconds.', answerRejected: 'Answer rejected.', answerConfirmFailed: 'The answer was not confirmed. Select it again to retry safely.',
    invalidCredentials: 'Invalid email or password.', accountExists: 'An account with that information already exists.', authFailed: 'Authentication failed. Please try again.',
  },
  es: {
    languageLabel: 'Idioma', english: 'Inglés', spanish: 'Español', multiplayerArena: 'Arena multijugador', competitiveLobby: 'Lobby competitivo', playersOnline: '{count} jugadores en línea', inThisGame: '{count} en este juego', player: 'Jugador', logOut: 'Cerrar sesión', signIn: 'Iniciar sesión', register: 'Registrarse', loadingSession: 'Validando sesión...',
    loadingLobby: 'Cargando lobby...', centralLobby: 'Lobby central', chooseNext: 'Elige la próxima', fight: 'batalla.', selectGame: 'Elige un juego', selectGameDescription: 'Elige un juego, revisa tu rango y entra a una partida.', players: 'jugadores', findingMatch: 'Buscando partida...', quickMatch: 'Partida rápida', arenas: 'arenas', loadingLeaderboard: 'Cargando clasificación...', loadingStats: 'Cargando tus estadísticas...',
    selected: 'Seleccionado', arena: 'Arena', playingNow: '{count} jugando ahora', comingSoon: 'Próximamente', readyForMatch: 'Listo para jugar',
    myStats: 'Mis estadísticas', personal: 'Personal', leaderboard: 'Clasificación general', wins: '{count}V',
    availableRooms: 'Salas disponibles', noRooms: 'Aún no hay salas disponibles.', createFirstRoom: 'Crear la primera sala', creator: 'Creador: {name}', playersInside: '{count} jugadores dentro', joinRoom: 'Unirse a la sala',
    createRoom: 'Crear sala', newRoom: 'Nueva sala para {game}', close: 'Cerrar', roomName: 'Nombre de la sala', roomNamePlaceholder: 'Cazadores de flotas', roomNameHelp: 'Este es el nombre visible en Salas disponibles.', cancel: 'Cancelar', confirmRoom: 'Confirmar sala',
    failedLoad: 'No se pudo cargar. Inténtalo de nuevo.', retry: 'Reintentar', somethingWrong: 'Algo salió mal', unexpectedError: 'Ocurrió un error inesperado.', tryAgain: 'Intentar de nuevo', failedRooms: 'No se pudieron cargar las salas.', loadingMatchRoom: 'Cargando sala de partida...', playerOnline: '{count} jugador en línea', fastMatch: 'Partida rápida', back: 'Volver',
    loginReturn: 'Regreso competitivo', backToArena: 'De vuelta a', theArena: 'la arena.', loginDescription: 'Revisa tu progreso, vuelve al lobby y sigue mejorando tu rango en partidas competitivas con una experiencia más clara y dinámica.', todayOn: 'Hoy en PlayHub', loginPromo: 'Nuevos duelos, nuevas rachas, nuevas posiciones.', welcomeBack: 'Bienvenido de nuevo', loginPrompt: 'Inicia sesión y vuelve a competir donde lo dejaste.', email: 'Correo electrónico', password: 'Contraseña', enterPassword: 'Ingresa tu contraseña', hide: 'Ocultar', show: 'Mostrar', signingIn: 'Iniciando sesión...', enterLobby: 'Entrar al lobby', createAccount: 'Crear cuenta', forgotPassword: '¿Olvidaste tu contraseña?',
    newChallenger: 'Nuevo retador', buildTag: 'Crea tu', playerTag: 'nombre de jugador.', registerDescription: 'Crea tu perfil, entra al lobby y empieza a construir historial, rachas y posición en cada arena competitiva.', whyJoin: 'Por qué unirse', registerPromo: 'Salas privadas, estadísticas visibles y progreso que se siente en cada partida.', createYourAccount: 'Crea tu cuenta', registerPrompt: 'Crea tu perfil competitivo y entra al ecosistema de partidas, rankings y estadísticas.', username: 'Nombre de usuario', chooseUsername: 'Elige un nombre de usuario', createPassword: 'Crea una contraseña', confirmPassword: 'Confirmar contraseña', repeatPassword: 'Repite tu contraseña', passwordStrength: 'Seguridad de la contraseña:', startTyping: 'Empieza a escribir para medirla', passwordsMismatch: 'Las contraseñas no coinciden.', creatingAccount: 'Creando cuenta...', createProfile: 'Crear perfil de retador', alreadyAccount: '¿Ya tienes una cuenta?', weak: 'Débil', fair: 'Regular', good: 'Buena', strong: 'Fuerte',
    realtimeMinigames: 'Minijuegos multijugador en tiempo real', playLoud: 'Juega fuerte.', climbHarder: 'Sube más alto.', presentationDescription: 'PlayHub convierte minijuegos competitivos en una experiencia con identidad: salas en vivo, rivales reales, estadísticas claras y una interfaz que impulsa a jugar otra vez.', compete: 'Entrar a competir', viewArenas: 'Ver arenas', livePulse: 'Pulso en vivo', arenaPreview: 'Vista previa de arena', online: 'en línea', seasonalFocus: 'Enfoque de temporada', seasonalCopy: 'Gana una posición en el top semanal y desbloquea insignias visibles.', gameSelection: 'Selección de juegos', chooseArena: 'Elige tu arena', gamesDescription: 'Cada juego tiene ritmo, color y tensión propia. El objetivo no es solo jugar, sino volver porque tu perfil, tu ranking y tus resultados importan.', loadingGames: 'Cargando minijuegos...', readyNow: 'Listo ahora', comingNext: 'Próximamente', registeredPlayers: 'Jugadores registrados', matchesPlayed: 'Partidas jugadas', onlineNow: 'En línea ahora', activeArenas: 'Arenas activas', quickMatches: 'Partidas rápidas', quickMatchesCopy: 'Entra al lobby, elige modo y empieza a competir en segundos.', realRivals: 'Rivales reales', realRivalsCopy: 'Salas, matchmaking y enfrentamientos en vivo con otros jugadores.', visibleProgress: 'Progreso visible', visibleProgressCopy: 'Rankings, historial y estadísticas que convierten cada partida en avance.', chooseMinigame: 'Elige un minijuego con identidad propia', competeLive: 'Compite en vivo contra otros jugadores', improveElo: 'Sube tu ELO y mejora tu perfil', duel: 'Duelo 1v1', fastPace: 'Ritmo rápido', pairs: 'Parejas 1v1', realtime: 'Tiempo real', playing: '{count} jugando',
    connected: 'Conectado', connecting: 'Conectando', disconnected: 'Desconectado', room: 'Sala {name}', ticTacToe: 'Tres en raya', playerO: 'Jugador O', playersCount: '{count}/2 jugadores', victory: 'Victoria de {name}', draw: 'Empate', turn: 'Turno de {name}', yourTurn: 'Te toca jugar', status: 'Estado', restartGame: 'Reiniciar partida', backToLobby: 'Volver al lobby', connectingRoom: 'Conectando a la sala...', waitingSecond: 'Esperando al segundo jugador.', gameStarted: 'La partida ha comenzado.', gameRestarted: 'La partida se reinició.', playerLeft: 'Un jugador salió de la sala.', enteringRoom: 'Entrando a la sala {roomId}...', roomConnectFailed: 'No se pudo conectar con la sala.', moveRejected: 'La jugada no fue aceptada.', moveRecorded: 'La jugada ya estaba registrada.', moveConfirmFailed: 'No se pudo confirmar la jugada. Reinténtala para reconciliar el estado.', restartFailed: 'No se pudo reiniciar la partida.', gameFinishedWinner: 'Partida finalizada. Gana {name}.', gameFinishedDraw: 'Partida finalizada en empate.',
    memoryPairs: 'Memoria / Parejas', youPairs: 'Tú: {count} parejas', youWin: 'Ganaste.', opponentWins: 'Gana el rival.', resolvingCards: 'Resolviendo cartas...', flipCard: 'Tu turno: voltea una carta.', backMemory: 'Volver al lobby de Memoria', gameInProgress: 'Partida en curso.', flipRejected: 'Volteo rechazado.', flipConfirmFailed: 'No se confirmó el volteo. Selecciona la misma carta para reintentar de forma segura.',
    triviaQuiz: 'Trivia', answered: '{count}/10 respondidas', quizComplete: 'Trivia terminada', resultsRecorded: 'El servidor registró los resultados finales.', backTrivia: 'Volver al lobby de Trivia', questionProgress: 'Pregunta {current} de 10', answerIndependently: 'Responde de forma independiente. Las respuestas incorrectas agregan cinco segundos.', answerRejected: 'Respuesta rechazada.', answerConfirmFailed: 'No se confirmó la respuesta. Selecciónala otra vez para reintentar de forma segura.',
    invalidCredentials: 'Correo electrónico o contraseña inválidos.', accountExists: 'Ya existe una cuenta con esa información.', authFailed: 'La autenticación falló. Inténtalo de nuevo.',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => window.localStorage.getItem('playhub-language') === 'es' ? 'es' : 'en');

  useEffect(() => {
    window.localStorage.setItem('playhub-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: TranslationKey, values?: Record<string, string | number>) => {
    let value: string = translations[language][key];
    for (const [name, replacement] of Object.entries(values ?? {})) value = value.replaceAll(`{${name}}`, String(replacement));
    return value;
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}
